/**
 * HTML <link> snippets and site.webmanifest builders.
 */

export interface ManifestOptions {
  /** App name (single string) */
  name?: string
  /** Short name */
  shortName?: string
  /** Theme color */
  themeColor?: string
  /** Background color */
  backgroundColor?: string
  /** Include 192/512 as maskable purpose */
  maskable?: boolean
}

export interface WebManifestIcon {
  src: string
  sizes: string
  type: string
  purpose?: string
}

export interface WebManifest {
  name: string
  short_name: string
  icons: WebManifestIcon[]
  theme_color: string
  background_color: string
  display: string
}

export function buildWebManifest(opts: ManifestOptions = {}): WebManifest {
  const purpose = opts.maskable ? 'any maskable' : 'any'
  return {
    name: opts.name ?? 'My Site',
    short_name: opts.shortName ?? opts.name ?? 'My Site',
    icons: [
      {
        src: '/android-chrome-192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose,
      },
      {
        src: '/android-chrome-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose,
      },
    ],
    theme_color: opts.themeColor ?? '#ffffff',
    background_color: opts.backgroundColor ?? '#ffffff',
    display: 'standalone',
  }
}

export function buildWebManifestJson(opts: ManifestOptions = {}): string {
  return JSON.stringify(buildWebManifest(opts), null, 2)
}

/**
 * Build the HTML <link> snippet ready to paste into <head>.
 * Includes ICO, PNG fallbacks, apple-touch-icon (180) and webmanifest hint.
 */
export function buildHtmlSnippet(opts: { themeColor?: string } = {}): string {
  const theme = opts.themeColor ?? '#ffffff'
  return [
    '<!-- Favicon: generated by tool-favicon-generator / 由 Favicon 生成器生成 -->',
    '<link rel="icon" href="/favicon.ico" sizes="any">',
    '<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16.png">',
    '<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png">',
    '<link rel="icon" type="image/png" sizes="48x48" href="/favicon-48.png">',
    '<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180.png">',
    '<link rel="manifest" href="/site.webmanifest">',
    `<meta name="theme-color" content="${theme}">`,
  ].join('\n')
}
