import React, { useState, useCallback } from 'react'
import { Copy, Check, Download } from 'lucide-react'

type Platform = 'isc' | 'windows' | 'dnsmasq'

interface DhcpConfig {
  subnet: string
  mask: string
  gateway: string
  dns1: string
  dns2: string
  poolStart: string
  poolEnd: string
  leaseTime: number
  domain: string
  ntpServer: string
  serverIp: string
}

const DEFAULT: DhcpConfig = {
  subnet: '192.168.1.0',
  mask: '255.255.255.0',
  gateway: '192.168.1.1',
  dns1: '8.8.8.8',
  dns2: '8.8.4.4',
  poolStart: '192.168.1.100',
  poolEnd: '192.168.1.200',
  leaseTime: 86400,
  domain: 'local',
  ntpServer: '',
  serverIp: '192.168.1.1',
}

function generateIsc(c: DhcpConfig): string {
  return `# ISC DHCP Server Configuration
# Generated by Toolbox DHCP Config Generator

default-lease-time ${c.leaseTime};
max-lease-time ${c.leaseTime * 2};

subnet ${c.subnet} netmask ${c.mask} {
  range ${c.poolStart} ${c.poolEnd};
  option subnet-mask ${c.mask};
  option routers ${c.gateway};
  option domain-name-servers ${c.dns1}${c.dns2 ? ', ' + c.dns2 : ''};
${c.domain ? `  option domain-name "${c.domain}";
` : ''}${c.ntpServer ? `  option ntp-servers ${c.ntpServer};
` : ''}}`
}

function generateDnsmasq(c: DhcpConfig): string {
  const lease = c.leaseTime >= 3600 ? `${Math.floor(c.leaseTime / 3600)}h` : `${c.leaseTime}m`
  return `# dnsmasq DHCP Configuration
# Generated by Toolbox DHCP Config Generator

dhcp-range=${c.poolStart},${c.poolEnd},${c.mask},${lease}
dhcp-option=3,${c.gateway}
dhcp-option=6,${c.dns1}${c.dns2 ? ',' + c.dns2 : ''}${c.domain ? `
dhcp-option=15,${c.domain}` : ''}${c.ntpServer ? `
dhcp-option=42,${c.ntpServer}` : ''}
dhcp-authoritative`
}

function generateWindows(c: DhcpConfig): string {
  return `# Windows DHCP Server - PowerShell Script
# Generated by Toolbox DHCP Config Generator

$scopeName = "DHCP Scope"
$scopeId = "${c.subnet}"
$startRange = "${c.poolStart}"
$endRange = "${c.poolEnd}"
$subnetMask = "${c.mask}"

# Create scope
Add-DhcpServerv4Scope -Name $scopeName -StartRange $startRange -EndRange $endRange -SubnetMask $subnetMask -State Active

# Set options
Set-DhcpServerv4OptionValue -ScopeId $scopeId -Router "${c.gateway}"
Set-DhcpServerv4OptionValue -ScopeId $scopeId -DnsServer "${c.dns1}"${c.dns2 ? `,"${c.dns2}"` : ''}${c.domain ? `
Set-DhcpServerv4OptionValue -ScopeId $scopeId -DnsDomain "${c.domain}"` : ''}${c.ntpServer ? `
Set-DhcpServerv4OptionValue -ScopeId $scopeId -OptionId 42 -Value "${c.ntpServer}"` : ''}

# Set lease duration (seconds: ${c.leaseTime})
Set-DhcpServerv4Scope -ScopeId $scopeId -LeaseDuration ([TimeSpan]::FromSeconds(${c.leaseTime}))`
}

// 提取到组件外部，避免每次 render 重新创建导致 input 失焦
interface FieldProps {
  label: string
  value: string | number
  onChange: (value: string) => void
  placeholder?: string
  type?: string
}

function Field({ label, value, onChange, placeholder, type = 'text' }: FieldProps) {
  return (
    <div>
      <label className="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">{label}</label>
      <input
        type={type}
        value={value}
        onChange={e => onChange(e.target.value)}
        placeholder={placeholder}
        className="w-full px-2.5 py-1.5 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 font-mono text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
      />
    </div>
  )
}

export function DhcpConfigGen() {
  const [config, setConfig] = useState<DhcpConfig>(DEFAULT)
  const [platform, setPlatform] = useState<Platform>('isc')
  const [copied, setCopied] = useState(false)

  const update = useCallback((field: keyof DhcpConfig) => (value: string) => {
    setConfig(prev => ({ ...prev, [field]: field === 'leaseTime' ? parseInt(value) || 0 : value }))
  }, [])

  const output = platform === 'isc' ? generateIsc(config)
    : platform === 'dnsmasq' ? generateDnsmasq(config)
    : generateWindows(config)

  const copy = useCallback(async () => {
    await navigator.clipboard.writeText(output)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }, [output])

  const download = useCallback(() => {
    const ext = platform === 'windows' ? 'ps1' : 'conf'
    const blob = new Blob([output], { type: 'text/plain' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `dhcpd.${ext}`
    a.click()
  }, [output, platform])

  return (
    <div className="max-w-4xl mx-auto p-6 space-y-6">
      <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">DHCP 配置生成器</h1>
      <p className="text-gray-500 dark:text-gray-400">生成 ISC DHCP / dnsmasq / Windows Server DHCP 配置文件</p>

      <div className="flex gap-2">
        {(['isc', 'dnsmasq', 'windows'] as Platform[]).map(p => (
          <button key={p} onClick={() => setPlatform(p)}
            className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${
              platform === p ? 'bg-indigo-600 text-white' : 'bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600'
            }`}>
            {p === 'isc' ? 'ISC DHCP' : p === 'dnsmasq' ? 'dnsmasq' : 'Windows Server'}
          </button>
        ))}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-5 space-y-3">
          <h2 className="font-semibold text-gray-900 dark:text-gray-100 mb-2">网络配置</h2>
          <Field label="子网地址" value={config.subnet} onChange={update('subnet')} placeholder="192.168.1.0" />
          <Field label="子网掩码" value={config.mask} onChange={update('mask')} placeholder="255.255.255.0" />
          <Field label="默认网关" value={config.gateway} onChange={update('gateway')} placeholder="192.168.1.1" />
          <Field label="DNS 服务器 1" value={config.dns1} onChange={update('dns1')} placeholder="8.8.8.8" />
          <Field label="DNS 服务器 2（可选）" value={config.dns2} onChange={update('dns2')} placeholder="8.8.4.4" />
          <Field label="域名（可选）" value={config.domain} onChange={update('domain')} placeholder="local" />
        </div>
        <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-5 space-y-3">
          <h2 className="font-semibold text-gray-900 dark:text-gray-100 mb-2">地址池配置</h2>
          <Field label="地址池起始" value={config.poolStart} onChange={update('poolStart')} placeholder="192.168.1.100" />
          <Field label="地址池结束" value={config.poolEnd} onChange={update('poolEnd')} placeholder="192.168.1.200" />
          <Field label="租约时间（秒）" value={config.leaseTime} onChange={update('leaseTime')} placeholder="86400" type="number" />
          <Field label="NTP 服务器（可选）" value={config.ntpServer} onChange={update('ntpServer')} placeholder="192.168.1.1" />
        </div>
      </div>

      <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-5 space-y-3">
        <div className="flex items-center justify-between">
          <h2 className="font-semibold text-gray-900 dark:text-gray-100">生成配置</h2>
          <div className="flex gap-2">
            <button onClick={copy}
              className="flex items-center gap-1.5 px-3 py-1.5 text-sm rounded-lg bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-200 transition-colors">
              {copied ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
              {copied ? '已复制' : '复制'}
            </button>
            <button onClick={download}
              className="flex items-center gap-1.5 px-3 py-1.5 text-sm rounded-lg bg-indigo-600 text-white hover:bg-indigo-700 transition-colors">
              <Download className="w-4 h-4" /> 下载
            </button>
          </div>
        </div>
        <pre className="bg-gray-50 dark:bg-gray-900 rounded-lg p-4 text-xs font-mono text-gray-800 dark:text-gray-200 overflow-x-auto whitespace-pre-wrap">{output}</pre>
      </div>
    </div>
  )
}
